# Configurações de aplicação
spring:
  on-profiles: local
  application:
    name: api-orch-realtime-sensor

# Configurações do servidor
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method